import './global.css';

export const metadata = {
  title: 'Welcome to store',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen max-w-6xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
