import Footer from '../components/footer';
import Navbar from '../components/navbar';
import './global.css';

export const metadata = {
  title: 'Welcome to store',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen max-w-7xl flex flex-col mx-auto">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
